services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      - POSTGRES_DB=transactsync
      - POSTGRES_USER=transactsync
      - POSTGRES_PASSWORD=transactsync
    ports:
      - "5432:5432"
    # volumes:
    #   - hostPath:containerPath:rw

  transactsync:
    container_name: transactsync
    image: ghcr.io/manojmukkamala/transactsync-api:latest
    environment:
      - API_KEY=super-secret
      - DATABASE_URL=postgresql://transactsync:transactsync@postgres:5432/transactsync
    ports:
      - "8000:8000"
    # volumes:
    #   - hostPath:containerPath:rw